### ISSUE TITLE
Finalize cohesive learning objectives

### ISSUE THREAD

**Issue by k8hertweck** [fredhutchio/concepts_machine_learning#6]
Identify ~4 key learning objectives for entire course: what should participants be able to do after completing the material?

Each class should have ~4 key learning objectives that map to those for the class.

**Comment by lakikowolfe** [comment]
The first pass at these are logged here (beneath the objectives TA used)
https://github.com/fredhutchio/concepts_machine_learning/blob/lw-edits/notes.md
